[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.7", features = ["derive"] }
crossbeam-channel = "0.5.13"
crossterm = "0.27.0"
ratatui = "0.26.3"
simple-logging = "2.0.2"
log = "0.4.22"
anyhow = "1.0.93"
